### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by zidingz** [kcal-app/kcal#34]
Hey there!

I belong to an open source security research community, and a member (@0xamal) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by cdubz** [comment]
Thanks for the recommendation! Added a reference to huntr.dev, which I have used before.

**Comment by cdubz** [comment]
@zidingz any idea about this? —

https://github.com/kcal-app/kcal/commit/db055b934e1b93079c8b518129e686edd391ec66#commitcomment-57067557
