### ISSUE TITLE
 SQLSTATE[22003]: Numeric value out of range: 

### ISSUE THREAD

**Issue by TartesDaJulia** [kcal-app/kcal#37]
Trying to edit a recipe and adding above 99 grams of something gives error:

 SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'amount' at row 1 (SQL: update `ingredient_amounts` set `amount` = 100, `ingredient_amounts`.`updated_at` = 2021-10-31 15:03:27 where `id` = 7)

**Comment by cdubz** [comment]
Weird. Will look at this soon. In my use I definitely have values > 99 in ingredient amount fields 🤔

**Comment by TartesDaJulia** [comment]
Found out editing a food's serving size above 99 leads to a 500 server error, maybe it is connected?

**Comment by cdubz** [comment]
Ok -- I can indeed reproduce this on the demo. Just not on my own instance of the app. Interesting...

**Comment by cdubz** [comment]
This is fixed on `main` -- thanks for reporting!

**Comment by TheHairyGun** [comment]
Hate to bother, but any chance for this 0.8.1 to be released? I think that I'm running into this as the USDA provides measurements often in portions of 100g.
