### ISSUE TITLE
 installation issue

### ISSUE THREAD

**Issue by enoxos** [kcal-app/kcal#67]
Hello,

I have not been successful installing kcal manual type on an Ubuntu Server 22.04.4 LTS with Apache.

There is an issue on step 12 second line 

`...
php artisan elastic:migrate
...`

which yields the following error message: 

> Migrating: 2021_03_04_193043_create_foods_index
> 
> In 2021_03_04_193043_create_foods_index.php line 9:
> 
> Interface "ElasticMigrations\MigrationInterface" not found

Any hep would be appreciated.

**Comment by vinn2010** [comment]
Same issue.

**Comment by cdubz** [comment]
This is fixed on `main` -- thanks for flagging!
